version: '3.1'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper/config/:/conf/"
    environment:
      ZOO_MY_ID: 1
      # ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
