version: '3'
services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/conf:/etc/nginx/conf.d"
    ports:
      - "80:80"
