version: "3"

services:
  jenkins:
    image: jenkins/jenkins
    user: root
    container_name: jenkins
    read_only: false
    volumes:
      - /root/jenkins/data:/var/jenkins_home
    ports:
      - "800:8080"
      - "50000:50000"

