version: "3"
services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/log:/var/log/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin