version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - "/root/minio/data:/data"
      - "/root/minio/config:/root/.minio"
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=admin"
    ports:
      - "9001:9000"
      - "9002:9001"
    command: server /data --console-address ":9001"

