version: "3"

services:
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka
    user: root
    ports:
      - "9092:9092"
    volumes:
      - "${pwd}/data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes