version: '3'
services:
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    privileged: true
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /root/redis/data:/data
      - /root/redis/conf/redis.conf:/etc/redis/redis.conf
      - /root/redis/logs:/logs
    command: [ "redis-server","/etc/redis/redis.conf" ]
